apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  {{- if eq .Values.customDriverName.enabled true}}
    name: {{ printf "%s-%s" ( include "custom.namespace" . ) .Values.customDriverName.value }}
  {{- else }}
    name: csi-powermax
  {{- end }}
spec:
    attachRequired: true
    fsGroupPolicy: {{ .Values.fsGroupPolicy }}