apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-array-config
  namespace: {{ .Release.Namespace }}
data:
  powermax-array-config.yaml: |
    X_CSI_POWERMAX_PORTGROUPS: {{ .Values.global.portGroups | toYaml | default "" }}
    X_CSI_TRANSPORT_PROTOCOL: {{ .Values.global.transportProtocol | toYaml | default "" }}
    {{- $_ := first .Values.global.storageArrays }}
    {{- range $index, $value := .Values.global.storageArrays }}
    X_CSI_POWERMAX_ENDPOINT: {{ $value.endpoint | toYaml | default "" }}
    {{- end }}
    X_CSI_MANAGED_ARRAYS: {{ .Values.global.managedArrays | toYaml | default "" }}