# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # github actions
  - package-ecosystem: "github-actions"
    target-branch: "release-v1.12.0"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
      day: "saturday"
    groups:
      github-actions:
        patterns:
          - "*"

  # csi-powerstore packages
  - package-ecosystem: docker
    target-branch: "release-v1.12.0"
    directories:
      - /charts/csi-powerstore
    labels:
      - dependencies
    schedule:
      # check daily
      interval: daily
      # at 6pm UTC
      time: "18:00"
    groups:
      csi-powerstore:
        patterns:
          - "*"

  # csi-isilon packages
  - package-ecosystem: docker
    target-branch: "release-v1.12.0"
    directories:
      - /charts/csi-isilon
    labels:
      - dependencies
    schedule:
      # check daily
      interval: daily
      # at 6pm UTC
      time: "18:00"
    groups:
      csi-isilon:
        patterns:
          - "*"

  # csi-vxflexos packages
  - package-ecosystem: docker
    target-branch: "release-v1.12.0"
    directories:
      - /charts/csi-vxflexos
    labels:
      - dependencies
    schedule:
      # check daily
      interval: daily
      # at 6pm UTC
      time: "18:00"
    groups:
      csi-vxflexos:
        patterns:
          - "*"
  # csi-unity packages
  - package-ecosystem: docker
    target-branch: "release-v1.12.0"
    directories:
      - /charts/csi-unity
    labels:
      - dependencies
    schedule:
      # check daily
      interval: daily
      # at 6pm UTC
      time: "18:00"
    groups:
      csi-unity:
        patterns:
          - "*"

  # csi-powermax packages
  - package-ecosystem: docker
    target-branch: "release-v1.12.0"
    directories:
      - /charts/csi-powermax
    labels:
      - dependencies
    schedule:
      # check daily
      interval: daily
      # at 6pm UTC
      time: "18:00"
    groups:
      csi-powermax:
        patterns:
          - "*"

  # csm-authorization packages
  - package-ecosystem: docker
    target-branch: "release-v1.12.0"
    directories:
      - /charts/csm-authorization
      - /charts/csm-authorization-v2.0
    labels:
      - dependencies
    schedule:
      # check daily
      interval: daily
      # at 6pm UTC
      time: "18:00"
    groups:
      csm-authorization:
        patterns:
          - "*"

  # karavi-observability packages
  - package-ecosystem: docker
    target-branch: "release-v1.12.0"
    directories:
      - /charts/karavi-observability
    labels:
      - dependencies
    schedule:
      # check daily
      interval: daily
      # at 6pm UTC
      time: "18:00"
    ignore:
      # ignore all updates to otel/opentelemetry-collector
      - dependency-name: "otel/opentelemetry-collector"
    groups:
      karavi-observability:
        patterns:
          - "*"

  # csm-replication packages
  - package-ecosystem: docker
    target-branch: "release-v1.12.0"
    directories:
      - /charts/csm-replication
    labels:
      - dependencies
    schedule:
      # check daily
      interval: daily
      # at 6pm UTC
      time: "18:00"
    groups:
      csm-replication:
        patterns:
          - "*"

  # csm-installer packages
  - package-ecosystem: docker
    target-branch: "release-v1.12.0"
    directories:
      - /charts/csm-installer
    labels:
      - dependencies
    schedule:
      # check daily
      interval: daily
      # at 6pm UTC
      time: "18:00"
    groups:
      csm-installer:
        patterns:
          - "*"
