apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "rekeys.encryption.storage.dell.com"
spec:
  group: "encryption.storage.dell.com"
  scope: "Cluster"
  names:
    plural: "rekeys"
    singular: "rekey"
    kind: "Rekey"
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required: ["spec"]
        properties:
          spec:
            required: ["persistentVolumeName"]
            type: object
            properties:
              persistentVolumeName:
                description: "PersistentVolume Name of the encrypted volume that will be rekeyed."
                type: "string"
          status:
            description: "Status of the rekey operation."
            type: object
            properties:
              phase:
                type: string
    # subresources
    subresources:
      status: {}
