---
# k8s/driver attributes

# "version" is used to verify the values file matches driver version
# Not recommend to change
version: v2.11.0

# "images" defines every container images used for the driver and its sidecars.
#  To use your own images, or a private registry, change the values here.

images:
  # "driver" defines the container image, used for the driver container.
  driver: dellemc/csi-vxflexos:v2.11.0
  # "powerflexSdc" defines the SDC image for init container.
  powerflexSdc: dellemc/sdc:4.5.2.1
  # CSI sidecars
  attacher: registry.k8s.io/sig-storage/csi-attacher:v4.6.1
  provisioner: registry.k8s.io/sig-storage/csi-provisioner:v5.0.1
  snapshotter: registry.k8s.io/sig-storage/csi-snapshotter:v8.0.1
  resizer: registry.k8s.io/sig-storage/csi-resizer:v1.11.1
  registrar: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.1
  healthmonitor: registry.k8s.io/sig-storage/csi-external-health-monitor-controller:v0.12.1
  # CSM sidecars
  replication: dellemc/dell-csi-replicator:v1.9.0
  vgsnapshotter: dellemc/csi-volumegroup-snapshotter:v1.6.0
  podmon: dellemc/podmon:v1.10.0
  authorization: dellemc/csm-authorization-sidecar:v1.11.0

# Represents number of certificate secrets, which user is going to create for ssl authentication. (vxflexos-cert-0..vxflexos-cert-n)
# If user does not use certificate, set to 0
certSecretCount: 0

# CSI driver log level
# Allowed values: "error", "warn"/"warning", "info", "debug"
# Default value: "debug"
logLevel: "debug"

# CSI driver log format
# Allowed values: "TEXT" or "JSON"
# Default value: "TEXT"
logFormat: "TEXT"

# Specify kubelet config dir path.
# Ensure that the config.yaml file is present at this path.
# Default value: /var/lib/kubelet
kubeletConfigDir: /var/lib/kubelet

# "defaultFsType" is used to set the default FS type which will be used
# for mount volumes if FsType is not specified in the storage class
# Allowed values: ext4, xfs
# Default value: none
defaultFsType: ext4

# imagePullPolicy: Policy to determine if the image should be pulled prior to starting the container.
# Allowed values:
#  Always: Always pull the image.
#  IfNotPresent: Only pull the image if it does not already exist on the node.
#  Never: Never pull the image.
# Default value: None
imagePullPolicy: IfNotPresent

# externalAccess: allows to specify additional entries for hostAccess of NFS volumes. Both single IP address and subnet are valid entries.
# Allowed Values: x.x.x.x/xx or x.x.x.x
# Default Value: None
externalAccess:

# enableQuota: a boolean that, when enabled, will set quota limit for a newly provisioned NFS volume.
# Allowed values:
#   true: set quota for volume
#   false: do not set quota for volume
# Optional: true
# Default value: none
enableQuota: false

# "enablesnapshotcgdelete"- a boolean that, when enabled, will delete all snapshots in a consistency group
# everytime a snap in the group is deleted
# Allowed values: true, false
# Default value: none
enablesnapshotcgdelete: "false"

# "enablelistvolumesnapshot" - a boolean that, when enabled, will allow list volume operation to include snapshots (since creating a volume
# from a snap actually results in a new snap)
# It is recommended this be false unless instructed otherwise.
# Allowed values: true, false
# Default value: none
enablelistvolumesnapshot: "false"

# Setting allowRWOMultiPodAccess to "true" will allow multiple pods on the same node
# to access the same RWO volume. This behavior conflicts with the CSI specification version 1.3
# NodePublishVolume descrition that requires an error to be returned in this case.
# However, some other CSI drivers support this behavior and some customers desire this behavior.
# Kubernetes could make a change at their discretion that would preclude our ability to support this option.
# Customers use this option at their own risk.
# You should leave this set as "false" unless instructed to change it by Dell support.
# Allowed values: true, false
# Default value: "false"
allowRWOMultiPodAccess: "false"

# fsGroupPolicy: Defines if the underlying volume supports changing ownership and permission of the volume before being mounted.
# Allowed values:
#   ReadWriteOnceWithFSType: supports volume ownership and permissions change only if the fsType is defined
#   and the volume's accessModes contains ReadWriteOnce.
#   File: kubernetes may use fsGroup to change permissions and ownership of the volume
#   to match user requested fsGroup in the pod's security policy regardless of fstype or access mode.
#   None: volumes will be mounted with no modifications.
fsGroupPolicy: File

# maxVxflexosVolumesPerNode: Specify default value for maximum number of volumes that controller can publish to the node.
# If value is zero CO SHALL decide how many volumes of this type can be published by the controller to the node.
# This limit is applicable to all the nodes in the cluster for which node label 'maxVxflexosVolumesPerNode' is not set.
# Allowed values: n, where n >= 0
# Default value: 0
maxVxflexosVolumesPerNode: 0

# "controller" allows to configure controller specific parameters
controller:
  # replication: allows to configure replication
  # Replication CRDs must be installed before installing driver
  replication:
    # enabled: Enable/Disable replication feature
    # Allowed values:
    #   true: enable replication feature(install dell-csi-replicator sidecar)
    #   false: disable replication feature(do not install dell-csi-replicator sidecar)
    # Default value: false
    enabled: false

    # replicationContextPrefix: prefix to use for naming of resources created by replication feature
    # Allowed values: string
    # Default value: powerflex
    replicationContextPrefix: "powerflex"

    # replicationPrefix: prefix to prepend to storage classes parameters
    # Allowed values: string
    # Default value: replication.storage.dell.com
    replicationPrefix: "replication.storage.dell.com"

  healthMonitor:
    # enabled: Enable/Disable health monitor of CSI volumes
    # Allowed values:
    #   true: enable checking of health condition of CSI volumes
    #   false: disable checking of health condition of CSI volumes
    # Default value: None
    enabled: false

    # interval: Interval of monitoring volume health condition
    # Allowed values: Number followed by unit (s,m,h)
    # Examples: 60s, 5m, 1h
    # Default value: 60s
    interval: 60s

  # volumeNamePrefix- defines a string prepended to each volume created by the CSI driver.
  # Default value: none
  # Examples: "k8s", "app1"
  volumeNamePrefix: k8s

  # "controllerCount" defines the number of VxFlex controller pods to deploy
  # Allowed values: n, where n > 0
  # Default value: none
  controllerCount: 2

  snapshot:
    # enabled: Enable/Disable volume snapshot feature
    # Allowed values:
    #   true: enable volume snapshot feature(install snapshotter sidecar)
    #   false: disable volume snapshot feature(do not install snapshotter sidecar)
    # Default value: None
    enabled: true

  resizer:
    # enabled: Enable/Disable volume expansion feature
    # Allowed values:
    #   true: enable volume expansion feature(install resizer sidecar)
    #   false: disable volume snapshot feature(do not install resizer sidecar)
    # Default value: None
    enabled: true

  # "controller.nodeSelector" defines what nodes would be selected for pods of controller deployment
  # Leave as blank to use all nodes
  # Allowed values: map of key-value pairs
  # Default value: None
  # Examples:
  #  node-role.kubernetes.io/control-plane: ""
  nodeSelector:
  #  node-role.kubernetes.io/control-plane: ""

  # "controller.tolerations" defines tolerations that would be applied to controller deployment
  # Leave as blank to install controller on worker nodes
  # Default value: None
  tolerations:
  # Uncomment if nodes you wish to use have the node-role.kubernetes.io/master taint
  # - key: "node-role.kubernetes.io/master"
  #   operator: "Exists"
  #   effect: "NoSchedule"
  # Uncomment if nodes you wish to use have the node-role.kubernetes.io/control-plane taint
  # - key: "node-role.kubernetes.io/control-plane"
  #   operator: "Exists"
  #   effect: "NoSchedule"

# "node" allows to configure node specific parameters
node:
  healthMonitor:
    # enabled: Enable/Disable health monitor of CSI volumes- volume usage, volume condition
    # Allowed values:
    #   true: enable checking of health condition of CSI volumes
    #   false: disable checking of health condition of CSI volumes
    # Default value: None
    enabled: false

  # "node.nodeSelector" defines what nodes would be selected for pods of node daemonset
  # Leave as blank to use all nodes
  # Allowed values: map of key-value pairs
  # Default value: None
  # Examples:
  #  node-role.kubernetes.io/control-plane: ""
  nodeSelector:
  #  node-role.kubernetes.io/control-plane: ""

  # "node.tolerations" defines tolerations that would be applied to node daemonset
  # Leave as blank to install node driver only on worker nodes
  # Default value: None
  tolerations:
  # Uncomment if nodes you wish to use have the node-role.kubernetes.io/master taint
  # - key: "node-role.kubernetes.io/master"
  #   operator: "Exists"
  #   effect: "NoSchedule"
  # Uncomment if nodes you wish to use have the node-role.kubernetes.io/control-plane taint
  # - key: "node-role.kubernetes.io/control-plane"
  #   operator: "Exists"
  #   effect: "NoSchedule"
  # Uncomment if CSM for Resiliency and CSI Driver pods monitor is enabled
  # - key: "offline.vxflexos.storage.dell.com"
  #   operator: "Exists"
  #   effect: "NoSchedule"
  # - key: "vxflexos.podmon.storage.dell.com"
  #   operator: "Exists"
  #   effect: "NoSchedule"
  # - key: "offline.unity.storage.dell.com"
  #   operator: "Exists"
  #   effect: "NoSchedule"
  # - key: "unity.podmon.storage.dell.com"
  #   operator: "Exists"
  #   effect: "NoSchedule"
  # - key: "offline.isilon.storage.dell.com"
  #   operator: "Exists"
  #   effect: "NoSchedule"
  # - key: "isilon.podmon.storage.dell.com"
  #   operator: "Exists"
  #   effect: "NoSchedule"

  # "renameSDC" defines the rename operation for SDC
  # Default value: None
  renameSDC:
    # enabled: Enable/Disable rename of SDC
    # Allowed values:
    #   true: enable renaming
    #   false: disable renaming
    # Default value: "false"
    enabled: false
    # "prefix" defines a string for prefix of the SDC name.
    # "prefix" + "worker_node_hostname" should not exceed 31 chars.
    # Default value: none
    # Examples: "rhel-sdc", "sdc-test"
    prefix: "sdc-test"

  # "approveSDC" defines the approve operation for SDC
  # Default value: None
  approveSDC:
    # enabled: Enable/Disable SDC approval
    # Allowed values:
    #  true: Driver will attempt to approve restricted SDC by GUID during setup
    #  false: Driver will not attempt to approve restricted SDC by GUID during setup
    # Default value: false
    enabled: false

# Storage Capacity Tracking
# Note: Capacity tracking is supported in kubernetes v1.24 and above, this feature will be automatically disabled in older versions.
storageCapacity:
  # enabled : Enable/Disable storage capacity tracking
  # Allowed values:
  #   true: enable storage capacity tracking
  #   false: disable storage capacity tracking
  # Default value: true
  enabled: true
  # pollInterval : Configure how often external-provisioner polls the driver to detect changed capacity
  # Allowed values: 1m,2m,3m,...,10m,...,60m etc
  # Default value: 5m
  pollInterval: 5m

# monitoring pod details
# These options control the running of the monitoring container
# This container gather diagnostic information in case of failure
monitor:
  # enabled allows the usage of the monitoring pod to be disabled
  # Allowed values: true, false
  # Default value: "false"
  enabled: false

  # hostNetwork determines if the monitor pod should run on the host network or not
  # Allowed values: true, false
  # Default value: "false"
  hostNetwork: true

  # hostPID determines if the monitor pod should run in the host namespace
  # Allowed values: true, false
  # Default value: "false"
  hostPID: true

# CSM module attributes

# volume group snapshotter(vgsnapshotter) details
# These options control the running of the vgsnapshotter container
vgsnapshotter:
  enabled: false

# Podmon is an optional feature under development and tech preview.
# Enable this feature only after contact support for additional information
podmon:
  enabled: false

  controller:
    args:
      - "--csisock=unix:/var/run/csi/csi.sock"
      - "--labelvalue=csi-vxflexos"
      - "--mode=controller"
      - "--skipArrayConnectionValidation=false"
      - "--driver-config-params=/vxflexos-config-params/driver-config-params.yaml"
      - "--driverPodLabelValue=dell-storage"
      - "--ignoreVolumelessPods=false"
  node:
    args:
      - "--csisock=unix:/var/lib/kubelet/plugins/vxflexos.emc.dell.com/csi_sock"
      - "--labelvalue=csi-vxflexos"
      - "--mode=node"
      - "--leaderelection=false"
      - "--driver-config-params=/vxflexos-config-params/driver-config-params.yaml"
      - "--driverPodLabelValue=dell-storage"
      - "--ignoreVolumelessPods=false"

# CSM module attributes
# authorization: enable csm-authorization for RBAC
# Deploy and configure authorization before installing driver
# Allowed values:
#   "true" - authorization is enabled
#   "false" - authorization is disabled
# Default value: "false"
authorization:
  enabled: false

  # proxyHost: hostname of the csm-authorization server
  # Default value: None
  proxyHost:

  # skipCertificateValidation: certificate validation of the csm-authorization server
  # Allowed Values:
  #   "true" - TLS certificate verification will be skipped
  #   "false" - TLS certificate will be verified
  # Default value: "true"
  skipCertificateValidation: true

sdcConfig:
  repo_address: "sftp://mft.dell.com/"
  repo_user: "PowerFlexRepo"
  # encoded base64 value of repo_public_rsa_key: cat repo_public_rsa_key | base64
  publicKey: bWZ0LmRlbGwuY29tIHNzaC1yc2EgQUFBQUIzTnphQzF5YzJFQUFBQURBUUFCQUFBQkFRQ29xTlFFVEl3NGNURzQ2TWNzUzRpUWN2b1R2UWM0M0J4NjJUejJYZzRtWkNESzRXTGpXVXZtTk9uUUpHQkJJaVdUczJTUTYvVmF2aDJjSjZOM3p5bFVjUnRxNE5WaVl0NDFtN1IvUmRNaG9vcTg0c0ZDYU9sNzlWV2lxZSsrazNCTWVabktLT2JSbENyaFY2SkhCcDh6Z1JhVWZZTkFzcjdxaDAwdk56TENQWDRvVTBjdzhjVW1BVFI4QzExZllUOEtsczEwaE9XcVovTGNsTmplbjB1SkYrQ3BvbWVua1hEOEtoMXlEOFlpRUh4eHl5K1NWMllQK3JDL3grVHNHb1lZR1oweWppRlNseWNDaWIyRER1L25CdnJmcjA4UG1yZHh0YjgzL3dEdkJFQlgzdnloR0tSSnZiVk11U1ZyQk5aSC95R3BDalg3MTg1TUhlMFByd3VYCjEwLjE0My4yMzguMjQ5IHNzaC1yc2EgQUFBQUIzTnphQzF5YzJFQUFBQURBUUFCQUFBQkFRQ29xTlFFVEl3NGNURzQ2TWNzUzRpUWN2b1R2UWM0M0J4NjJUejJYZzRtWkNESzRXTGpXVXZtTk9uUUpHQkJJaVdUczJTUTYvVmF2aDJjSjZOM3p5bFVjUnRxNE5WaVl0NDFtN1IvUmRNaG9vcTg0c0ZDYU9sNzlWV2lxZSsrazNCTWVabktLT2JSbENyaFY2SkhCcDh6Z1JhVWZZTkFzcjdxaDAwdk56TENQWDRvVTBjdzhjVW1BVFI4QzExZllUOEtsczEwaE9XcVovTGNsTmplbjB1SkYrQ3BvbWVua1hEOEtoMXlEOFlpRUh4eHl5K1NWMllQK3JDL3grVHNHb1lZR1oweWppRlNseWNDaWIyRER1L25CdnJmcjA4UG1yZHh0YjgzL3dEdkJFQlgzdnloR0tSSnZiVk11U1ZyQk5aSC95R3BDalg3MTg1TUhlMFByd3VYCg==
  # encoded base64 value of user_private_rsa_key: cat user_private_rsa_key | base64
  privateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUNGd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFnRUFvM21XUC9VQmpBc0NJOG5NaWFjaUkxdGs0cmNPT3ljeG55dEhJT3kvNGVySnR0U3VPeEM2CitSTlZ4R25BL3pkelE4NjdlKysrL0dGempDZHY3QlE5QXAwUThVMGtyNFNBbG5meGJxanRpY2grWG5POGFIaDlndGxGNkMKRFpOamFLdWhjb3hrakx0azRsb2FoTUlhOGdMV1pMUXQxTzRwR2dwdVArR3JIZ3EvR1NiZEJSYkVCTzJRTUF6ZU9COGZDMAo3OXJEOGNaWno2ZzgvRU9GMUdBMGFjOUZjTG4yTmExMGE1WmNXR1hGUG1OVDViU0xONUJjMWllNi9YTUNlanJha1lZZmJUCjNteXBHamdIdDc3aVBsclZLN2NhK3NYS0dwS0FjVy9JSFRtakoyQ2VseVI1cmRNcmcyQkg4b2dsUk1mazdmajQvYnB4MS8KN0tzWGNxS2RZZTZXVkpHbjgxNkpoa0puSzBnVkFPd3h1Z2puTGViREJYOXFzTm9ydVIxZWFHcEJDSEZuZ0tGaEM0d295cAo2K1llNW9UVHFHVk03cXJleUlOS3NoekE4UmtSZ3NLZGhBMEdKaHN5TjVGa0ZaMHVFdzJ2a1FMelQwdFN0T1pGTGpPQnQ3CkdzdHRhRldVY1hhNGtvMVlzY2JNODBRSktGUXFTYmVudzQycDY2RmQwWUFlT1k5OEpyenhNSkNNT3NMK29OS08vMVAzL0oKbTBQUzN2UFdwTkZRRXBubGFsa0pQcHBRUFE3T1Jud3lTWTMwQ3JXNjhKSFdXQTdNRnNyU2JaYittYmJZdkd5NFNQM1hGLwpBQzRhazIrTHc3dFZaSURkU25uSW93bHRkeWUvVGFjdk9XTUFOKzlFeHNQdzd3TE82eVcrSnVOZUpnSDNVcE9aOW5mcFJvCmNBQUFkWTVvakNXdWFJd2xvQUFBQUhjM05vTFhKellRQUFBZ0VBbzNtV1AvVUJqQXNDSThuTWlhY2lJMXRrNHJjT095Y3gKbnl0SElPeS80ZXJKdHRTdU94QzYrUk5WeEduQS96ZHpRODY3ZSsrKy9HRnpqQ2R2N0JROUFwMFE4VTBrcjRTQWxuZnhicQpqdGljaCtYbk84YUhoOWd0bEY2Q0RaTmphS3VoY294a2pMdGs0bG9haE1JYThnTFdaTFF0MU80cEdncHVQK0dySGdxL0dTCmJkQlJiRUJPMlFNQXplT0I4ZkMwNzlyRDhjWlp6Nmc4L0VPRjFHQTBhYzlGY0xuMk5hMTBhNVpjV0dYRlBtTlQ1YlNMTjUKQmMxaWU2L1hNQ2VqcmFrWVlmYlQzbXlwR2pnSHQ3N2lQbHJWSzdjYStzWEtHcEtBY1cvSUhUbWpKMkNlbHlSNXJkTXJnMgpCSDhvZ2xSTWZrN2ZqNC9icHgxLzdLc1hjcUtkWWU2V1ZKR244MTZKaGtKbkswZ1ZBT3d4dWdqbkxlYkRCWDlxc05vcnVSCjFlYUdwQkNIRm5nS0ZoQzR3b3lwNitZZTVvVFRxR1ZNN3FyZXlJTktzaHpBOFJrUmdzS2RoQTBHSmhzeU41RmtGWjB1RXcKMnZrUUx6VDB0U3RPWkZMak9CdDdHc3R0YUZXVWNYYTRrbzFZc2NiTTgwUUpLRlFxU2Jlbnc0MnA2NkZkMFlBZU9ZOThKcgp6eE1KQ01Pc0wrb05LTy8xUDMvSm0wUFMzdlBXcE5GUUVwbmxhbGtKUHBwUVBRN09Sbnd5U1kzMENyVzY4SkhXV0E3TUZzCnJTYlpiK21iYll2R3k0U1AzWEYvQUM0YWsyK0x3N3RWWklEZFNubklvd2x0ZHllL1RhY3ZPV01BTis5RXhzUHc3d0xPNnkKVytKdU5lSmdIM1VwT1o5bmZwUm9jQUFBQURBUUFCQUFBQ0FCcUJZazBvYW9ITVh5SnlXOG1ONGNrZHpuTzcvb0MwMENUZwpuWDNISlMxNkpnNlEyVmNXVlZxQk9neklvTlJBcDEyOUxVVGhFSFJYVUtiTzFpVE8rejFyUGc0QjFncm5Udm9XcEh5dXd5ClR0N3g5ZFlKVUh4RUhzL0pxd2lNZHpmSGJEdm9hMzB0L1NOK1BJSjkvbVJ5OVZRS3FzdTFlZENSRkdNak1kMkRISXoxY2kKeWJEbGxHTTNTM0FXalVFdktBY2p6MVZxTmJHbnM0dXJYdzJhTTZWY1NBUUpBdFNkTlIwa21nQnpMOUgzeE9pZnAxcncregp4MTRLbXJkaUZmWFlUdTNEV1lMYzEyWTY0M1YxYTdWMGdNKy90bzRtZDZoclRJd1g5YmhYV2c3T2FhaFQ3NjZ4YUlLNm42Ci9CUjFtcGw0TEdOWWplTEFzN2NwM25sbHlHS1FOeDVLSDZwaXpFTjVZeXpSVkYrNDhEYnVaWmNsNDdTd1VMWm1CSFRhRlIKMlhWcW1Fa21XMHM4SDNaNWFVb0xIQy9UU1Q4elZpbnljRUI2UjdDbjVvYTZabmYra0wvN0pEU0xkNFVYMGxkRTBpc284QworMnVkdEMzamNsU2NMRVBPUFpzNldqeWtBYmE3bkRVM0puTVYvV0REdnArTXYrMmp4UVdjbmRSaW5kQXcraGNCQmJRMDE4Cms0bktBZVZTT3FzWmdTSmJkRnJPQkhEZStGczEwOUNOT3dBUzFCYkVHaWN4eDZJNXpnNXFnOXZyZFVzcmpKdk0wWVY5dDcKNjNORCsxTFFhQ1ZyTHVOaHgwUy9WRUZJbVREMHRuNG1iOGhaZEVacml0MUxTUFlZU2pxNGs4ZmJFYlYyNUF1TnlKS0hoawp6L1NVQmxIWkxHV0oyR2xvN3hBQUFCQUdtMTFqOVBFV2pKWU56UDNkeWpZei9kZERSRlcxeVdzNnRzeTlNR2wyWkVMSFJPCk5SS29HVFFGZGhFSTNWWTdmZ21tS0R6SlJCWTlUSk9xdWpPcDc2YWFwVFlXWHNLS0d5eFN3THlmNkd6Q1RweHJVeVdHdnUKRG9UYjJ3YlJqcUhNUDZCZ0ZMV2VDRW51SnZnOHJIZUtVaWpPajdaSFR4SEFhWlllanUxb2xzSnVMaytNY29JYkFqc1E0cQpRTHVmeXJYQjBPbUxSeDhjeHJRcWxvSWxTaHRnY21Ed1dFSE9Xc3BXN0FvUG8rRzluWHFBNkhVMjVZNlczWVRyM2ZCaTNzCncwYnFyQ3E5R3ZIUi9GV0p5TjA2MzM4N1lRajk3WEw2c2Q0ejlhR3J2eXFuYTNHWFpDM1BSOGgvY2lkT3VLMHNmRHhkVU8KMDZTLzV2Tk9rQmJ6NzVVQUFBRUJBTTZ4VmhaWGVsSlkrRTdhaVNabTBFNk9JbHpOQ0pMME1MU2lKUm9TZzQrTGczYUpEZQpkR1B4cmthNWdjUnJ4bjJ3YW55UTlMejA5d3pUdXBmM3NIQjhjM29UbkIxaDhEVURkQnlwTmVobTFJK1dyQlJydUF5QS94Ck1vaE1nMURob1FTMXpMUVhHUzF4ZGJIdGp1MXU2YWZDY01uYWhmKy83K1FGeUFTZURMdFpvcXdqVVQzSVJVaXUxT2dtTzUKdDREKzArZEFmR2hTVEZuR0N4UG16K1EybCsremE1TTBmMnhVMm5sVENZaVpIZUFYY2RONStPNFlnbXBoV1lYbXh5WnBUego1d3VTTkFrSXBCODhIVnRXMFdhbmdLZTVyNFU5ZGVZYUp6KzhPR0lES0p1bFd3YjRFaEI4YVI1a2NFY2N0Q0JxVzlJWWZOClBmdlFudTZTc2VYSjBBQUFFQkFNcDQ5RHlnNFJDbnRNdTc1WWRGYWNjNUhCRDhlY0g3eGM1MXMyK294cEx1bTVzQm9ZTzUKT0gwT1JKNEE1enZWSlBTWUFSVFVEUDZlc3VOTmErNmx5anZCZk94STM5Z1BWWmsvdlYySk5GcGQralFZSWZXMU5uT3ozMQpub1NzSkpTYjN2SkN3ZUFiZyszVEE0VXJXbThmdDRaZ1dYcExTeTlFK1g3VlJ4ZDByMDEwNnlmT1FSVTlROXgyOW1td0Z1Ckl3cDdhTUdTNkhaVGJmZzNob243b1lzdmRsZU4vWXFORlp5ejJUQ211ZCs5R24wMWphVWlnUEx5NXVjU2hGQlQ0UU85WWIKSG9hdUZ0NmZKY0szaE11cjBLQUNiWXlIbVVBYVdqbU5qVzIwVDdZR3pvOVhmZXN4T0Jrak5kZ1ZiWU9XMTdBSSt6UFAreApKZkk5MHBWT25ITUFBQUFmY205dmRFQjJiUzFoYm5OcFlteGxMbk5wYnk1c1lXSXVaVzFqTG1OdmJRRUNBd1E9Ci0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=