{{- if .Values.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cosi.roleBindingName" . }}
  labels:
    {{- include "cosi.labels" . | trim | nindent 4 }}
  {{- with .Values.rbac.roleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cosi.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "cosi.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
