{{- if .Values.configuration.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "cosi.secretName" . }}
  labels:
    {{- include "cosi.labels" . | trim | nindent 4 }}
  {{- with .Values.configuration.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: {{ toString .Values.configuration.data | b64enc }}
{{- end }}
