{{ if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cosi-driver.serviceAccountName" . }}
  labels:
    {{- include "cosi-driver.labels" . | trim | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end}}
