apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Release.Name }}-serving-cert
  name: {{ .Release.Name }}-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Release.Name }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-mobility-storage-dell-com-v1alpha1-backup
  failurePolicy: Fail
  name: mbackup.mobility.storage.dell.com
  rules:
  - apiGroups:
    - mobility.storage.dell.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backups
  sideEffects: None
