apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-serving-cert
  namespace: {{ include "custom.namespace" . }}
spec:
  dnsNames:
  - {{ .Release.Name }}-webhook-service.{{ include "custom.namespace" . }}.svc
  - {{ .Release.Name }}-webhook-service.{{ include "custom.namespace" . }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ .Release.Name }}-selfsigned-issuer
  secretName: webhook-server-cert
