apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - backups/finalizers
  verbs:
  - update
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - backups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - podvolumebackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - podvolumebackups/finalizers
  verbs:
  - update
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - podvolumebackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - podvolumerestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - podvolumerestores/finalizers
  verbs:
  - update
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - podvolumerestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - restores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - restores/finalizers
  verbs:
  - update
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - restores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - clusterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - clusterconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - mobility.storage.dell.com
  resources:
  - clusterconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotclasses
  verbs:
  - get
  - list
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  verbs:
  - get
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
- apiGroups:
  - velero.io
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velero.io
  resources:
  - backups/status
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - velero.io
  resources:
  - backups/finalizers
  verbs:
  - update
- apiGroups:
  - velero.io
  resources:
  - backupstoragelocations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velero.io
  resources:
  - deletebackuprequests
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - velero.io
  resources:
  - podvolumebackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velero.io
  resources:
  - podvolumebackups/finalizers
  verbs:
  - update
- apiGroups:
  - velero.io
  resources:
  - podvolumebackups/status
  verbs:
  - create
  - get
  - list
  - patch
  - update
- apiGroups:
  - velero.io
  resources:
  - podvolumerestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velero.io
  resources:
  - resticrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velero.io
  resources:
  - restores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - volumegroup.storage.dell.com
  resources:
  - dellcsivolumegroupsnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
    - mobility.storage.dell.com
  resources:
    - schedules
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - mobility.storage.dell.com
  resources:
    - schedules/status
  verbs:
    - get
    - patch
    - update
