apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webhook-service
  namespace: {{ include "custom.namespace" . }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
