name: redis-csm
redisSecretProviderClass:
  redisSecretName:
  redisUsernameKey:
  redisPasswordKey:
sentinel: sentinel
rediscommander: rediscommander
replicas: 5
images:
  redis:
    image: redis:8.2.0-alpine
  commander:
    image: rediscommander/redis-commander:latest
