redis:
  name: redis-csm
  sentinel: sentinel
  rediscommander: rediscommander
  replicas: 5
  images:
    redis: amaas-eos-mw1.cec.lab.emc.com:5046/redis:7.2.4-alpine
    commander: rediscommander/redis-commander:latest
