name: redis-csm
redisSecretProviderClass: ""
sentinel: sentinel
rediscommander: rediscommander
replicas: 5
images:
  redis:
    image: redis:7.4.3-alpine
  commander:
    image: rediscommander/redis-commander:latest
