receivers:
  otlp:
    protocols:
      grpc:
        tls_settings:
          cert_file: /etc/ssl/certs/cert.crt
          key_file: /etc/ssl/certs/cert.key
      http:
  
exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
  logging:
  
extensions:
  health_check: {}
  
service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging,prometheus]

