apiVersion: v2
appVersion: "0.1.1"
description: The open-source solution that provides Kubernetes administrators insight into the mapping between Kubernetes Persistent Volumes and Storage System Volumes.
name: karavi-topology
version: 0.1.1
