apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ include "custom.namespace" . }}
spec:
  type:
  clusterIP: None
  selector:
    app: {{ .Values.redis.name }}
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: {{ .Values.redis.name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ include "custom.namespace" . }}
spec:
  serviceName: {{ .Values.redis.name }}
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/redis-secret.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: config
        image: {{ .Values.redis.images.redis }}
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-csm-secret
                key: password

        command: [ "sh", "-c" ]
        args:
          - |
            cp /csm-auth-redis-cm/redis.conf /etc/redis/redis.conf
            echo "masterauth $REDIS_PASSWORD" >> /etc/redis/redis.conf
            echo "requirepass $REDIS_PASSWORD" >> /etc/redis/redis.conf
            
            echo "Finding master..."
            MASTER_FDQN=`hostname  -f | sed -e 's/{{ .Values.redis.name }}-[0-9]\./{{ .Values.redis.name }}-0./'`
            echo "Master at " $MASTER_FQDN
            if [ "$(redis-cli -h sentinel -p 5000 ping)" != "PONG" ]; then
              echo "No sentinel found..."
              if [ "$(hostname)" = "{{ .Values.redis.name }}-0" ]; then
                echo "This is Redis master, not updating redis.conf..."
              else
                echo "This is Redis replica, updating redis.conf..."               
                echo "replicaof $MASTER_FDQN 6379" >> /etc/redis/redis.conf                
              fi
            else
              echo "Sentinel found, finding master..."
              MASTER="$(redis-cli -h sentinel -p 5000 sentinel get-master-addr-by-name mymaster | grep -E '(^redis-csm-\d{1,})|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})')"              
              echo "replicaof $MASTER_FDQN 6379" >> /etc/redis/redis.conf 
            fi
        volumeMounts: 
        - name: redis-primary-volume
          mountPath: /data
        - name: configmap
          mountPath: /csm-auth-redis-cm/
        - name: config
          mountPath: /etc/redis/
      containers:
      - name: {{ .Values.redis.name }}
        image: {{ .Values.redis.images.redis }}
        command: ["redis-server"]
        args: ["/etc/redis/redis.conf"]
        ports:
        - containerPort: 6379
          name: {{ .Values.redis.name }}
        volumeMounts:
        - name: redis-primary-volume
          mountPath: /data
        - name: configmap
          mountPath: /csm-auth-redis-cm/
        - name: config
          mountPath: /etc/redis/
      volumes:
      - name: redis-primary-volume        
        emptyDir: {}
      - name: config 
        emptyDir: {}
      - name: configmap
        configMap:
          name: redis-csm-cm          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.rediscommander }}
  namespace: {{ include "custom.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.redis.rediscommander }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.rediscommander }}
        tier: backend
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/redis-secret.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Values.redis.rediscommander }}
        image: {{ .Values.redis.images.commander }}
        imagePullPolicy: IfNotPresent
        env:
          {{- $str := "" -}}
          {{- $ns := include "custom.namespace" . -}} 
          {{- $replicas := .Values.redis.replicas | int }}
          {{- $sentinel := .Values.redis.sentinel }}
          {{- range $i, $e := until $replicas }} 
          {{- if $i }}         
          {{- $str = print $str "," -}}
          {{- end }}           
          {{- $str = printf "%s%s-%d.%s.%s.svc.cluster.local:5000" $str $sentinel $i $sentinel $ns -}}
          {{- end }}
        - name: SENTINELS        
          value: {{ $str | quote }}                                     
        - name: K8S_SIGTERM
          value: "1"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-csm-secret
              key: password  
        - name: SENTINEL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-csm-secret
              key: password          
        - name: HTTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-csm-secret
              key: password          
        - name: HTTP_USER
          valueFrom:
            secretKeyRef:
              name: redis-csm-secret
              key: commander_user         
        ports:
        - name: {{ .Values.redis.rediscommander }}
          containerPort: 8081
        livenessProbe:
          httpGet:
            path: /favicon.png
            port: 8081
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "500m"
            memory: "512M"
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.rediscommander }}
  namespace: {{ include "custom.namespace" . }}
spec:
  selector:
    app: {{ .Values.redis.rediscommander }}
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
