{{- $redisSecretProviderClass := .Values.redisSecretProviderClass | default dict }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: {{ include "custom.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redis-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: redis
    namespace: {{ include "custom.namespace" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "custom.namespace" . }}
spec:
  type:
  clusterIP: None
  selector:
    app: {{ .Values.name }}
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: {{ .Values.name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "custom.namespace" . }}
spec:
  serviceName: {{ .Values.name }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/redis-secret.yaml") . | sha256sum }}
        {{- if and $redisSecretProviderClass (hasKey $redisSecretProviderClass "conjur") }}
        conjur.org/secrets: |
          {{- range $redisSecretProviderClass.conjur }}
          {{- range .paths }}
          - {{ .usernamePath }}: {{ .usernamePath | quote }}
          - {{ .passwordPath }}: {{ .passwordPath | quote }}
          {{- end }}
          {{- end }}
        {{- end }}
    spec:
      serviceAccountName: redis
      initContainers:
      - name: config
        image: {{ .Values.images.redis.image }}
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.redisSecretProviderClass.redisSecretName | default "redis-csm-secret" }}
                key: {{ .Values.redisSecretProviderClass.redisPasswordKey }}
        command: [ "sh", "-c" ]
        args:
          - |
            cp /csm-auth-redis-cm/redis.conf /etc/redis/redis.conf
            echo "masterauth $REDIS_PASSWORD" >> /etc/redis/redis.conf
            echo "requirepass $REDIS_PASSWORD" >> /etc/redis/redis.conf

            echo "Finding master..."
            MASTER_FDQN=`hostname  -f | sed -e 's/{{ .Values.name }}-[0-9]\./{{ .Values.name }}-0./'`
            echo "Master at " $MASTER_FDQN
            if [ "$(redis-cli -h sentinel -p 5000 ping)" != "PONG" ]; then
              echo "No sentinel found..."
              if [ "$(hostname)" = "{{ .Values.name }}-0" ]; then
                echo "This is Redis master, not updating redis.conf..."
              else
                echo "This is Redis replica, updating redis.conf..."
                echo "replicaof $MASTER_FDQN 6379" >> /etc/redis/redis.conf
              fi
            else
              echo "Sentinel found, finding master..."
              MASTER="$(redis-cli -h sentinel -p 5000 sentinel get-master-addr-by-name mymaster | grep -E '(^redis-\d{1,})|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})')"
              echo "replicaof $MASTER_FDQN 6379" >> /etc/redis/redis.conf
            fi
        volumeMounts:
        - name: redis-primary-volume
          mountPath: /data
        - name: configmap
          mountPath: /csm-auth-redis-cm/
        - name: config
          mountPath: /etc/redis/
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.images.redis.image }}
        command: ["redis-server"]
        args: ["/etc/redis/redis.conf"]
        ports:
        - containerPort: 6379
          name: {{ .Values.name }}
        volumeMounts:
        - name: redis-primary-volume
          mountPath: /data
        - name: configmap
          mountPath: /csm-auth-redis-cm/
        - name: config
          mountPath: /etc/redis/
        {{- if .Values.redisSecretProviderClass.redisSecretName }}
        - name: secrets-store-inline-redis
          mountPath: /etc/csm-authorization/redis
          readOnly: true
        {{- end }}
      volumes:
      - name: redis-primary-volume
        emptyDir: {}
      - name: config
        emptyDir: {}
      - name: configmap
        configMap:
          name: redis-cm
      {{- if .Values.redisSecretProviderClass.redisSecretName }}
      - name: secrets-store-inline-redis
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "{{ .Values.redisSecretProviderClass.redisSecretName }}"
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rediscommander }}
  namespace: {{ include "custom.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.rediscommander }}
  template:
    metadata:
      labels:
        app: {{ .Values.rediscommander }}
        tier: backend
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/redis-secret.yaml") . | sha256sum }}
        {{- if and $redisSecretProviderClass (hasKey $redisSecretProviderClass "conjur") }}
        conjur.org/secrets: |
          {{- range $redisSecretProviderClass.conjur }}
          {{- range .paths }}
          - {{ .usernamePath }}: {{ .usernamePath | quote }}
          - {{ .passwordPath }}: {{ .passwordPath | quote }}
          {{- end }}
          {{- end }}
        {{- end }}
    spec:
      serviceAccountName: redis
      containers:
      - name: {{ .Values.rediscommander }}
        image: {{ .Values.images.commander.image }}
        imagePullPolicy: IfNotPresent
        env:
          {{- $str := "" -}}
          {{- $ns := include "custom.namespace" . -}}
          {{- $replicas := .Values.replicas | int }}
          {{- $sentinel := .Values.sentinel }}
          {{- range $i, $e := until $replicas }}
          {{- if $i }}
          {{- $str = print $str "," -}}
          {{- end }}
          {{- $str = printf "%s%s-%d.%s.%s.svc.cluster.local:5000" $str $sentinel $i $sentinel $ns -}}
          {{- end }}
        - name: SENTINELS
          value: {{ $str | quote }}
        - name: K8S_SIGTERM
          value: "1"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redisSecretProviderClass.redisSecretName | default "redis-csm-secret" }}
              key: {{ .Values.redisSecretProviderClass.redisPasswordKey }}
        - name: SENTINEL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redisSecretProviderClass.redisSecretName | default "redis-csm-secret" }}
              key: {{ .Values.redisSecretProviderClass.redisPasswordKey }}
        - name: HTTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redisSecretProviderClass.redisSecretName | default "redis-csm-secret" }}
              key: {{ .Values.redisSecretProviderClass.redisPasswordKey }}
        - name: HTTP_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redisSecretProviderClass.redisSecretName | default "redis-csm-secret" }}
              key: {{ .Values.redisSecretProviderClass.redisUsernameKey }}
        ports:
        - name: {{ .Values.rediscommander }}
          containerPort: 8081
        livenessProbe:
          httpGet:
            path: /favicon.png
            port: 8081
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "500m"
            memory: "512M"
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        {{- if .Values.redisSecretProviderClass.redisSecretName }}
        volumeMounts:
        - name: secrets-store-inline-redis
          mountPath: /etc/csm-authorization/redis
          readOnly: true
        {{- end }}
      {{- if .Values.redisSecretProviderClass.redisSecretName }}
      volumes:
      - name: secrets-store-inline-redis
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "{{ .Values.redisSecretProviderClass.redisSecretName }}"
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rediscommander }}
  namespace: {{ include "custom.namespace" . }}
spec:
  selector:
    app: {{ .Values.rediscommander }}
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
