{{- if not .Values.redisSecretProviderClass.redisSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-csm-secret
  namespace: {{ include "custom.namespace" . }}
type: kubernetes.io/basic-auth
stringData:
  password: {{ required "Redis credentials are required. Either set redis.redisPassword or configure redis.redisSecretProviderClass to use a Secret Store CSI driver." .Values.redisPassword }}
  commander_user: {{ required "Redis credentials are required. Either set redis.redisUsername or configure redis.redisSecretProviderClass to use a Secret Store CSI driver." .Values.redisUsername }}
{{- end }}
