{{- if not .Values.redisSecretProviderClass.redisSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-csm-secret
  namespace: {{ include "custom.namespace" . }}
type: kubernetes.io/basic-auth
stringData:
  {{ .Values.redisSecretProviderClass.redisPasswordKey | default "K@ravi123!" }}: K@ravi123!
  {{ .Values.redisSecretProviderClass.redisUsernameKey | default "dev" }}: dev
{{- end }}
