{{- $redisSecretProviderClass := .Values.redisSecretProviderClass | default dict }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentinel
  namespace: {{ include "custom.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sentinel-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: sentinel
    namespace: {{ include "custom.namespace" . }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.sentinel }}
spec:
  serviceName: {{ .Values.sentinel }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.sentinel }}
  template:
    metadata:
      labels:
        app: {{ .Values.sentinel }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/redis-secret.yaml") . | sha256sum }}
        {{- if hasKey $redisSecretProviderClass "conjur" }}
        conjur.org/secrets: |
          {{- range $redisSecretProviderClass.conjur }}
          {{- range .paths }}
          - {{ .usernamePath }}: {{ .usernamePath | quote }}
          - {{ .passwordPath }}: {{ .passwordPath | quote }}
          {{- end }}
          {{- end }}
        {{- end }}
    spec:
      serviceAccountName: sentinel
      initContainers:
      - name: config
        image: {{ .Values.images.redis.image }}
        command: [ "sh", "-c" ]
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.redisSecretProviderClass.redisSecretName | default "redis-csm-secret" }}
                key: {{ .Values.redisSecretProviderClass.redisPasswordKey }}
        args:
          - |
            replicas=$( expr {{ .Values.replicas | int }} - 1)
            for i in $(seq 0 $replicas)
            do
                node=$( echo "{{ .Values.name }}-$i.{{ .Values.name }}" )
                nodes=$( echo "$nodes*$node" )
            done
            loop=$(echo $nodes | sed -e "s/"*"/\n/g")

            foundMaster="false"
            while [ "$foundMaster" != "true" ]
            do
                for i in $loop
                do
                    echo "Finding master at $i"
                    MASTER=$(redis-cli --no-auth-warning --raw -h $i -a $REDIS_PASSWORD info replication | awk '{print $1}' | grep master_host: | cut -d ":" -f2)
                    if [ "$MASTER" = "" ]; then
                        echo "Master not found..."
                        echo "Sleeping 5 seconds for pods to come up..."
                        sleep 5
                        MASTER=
                    else
                        echo "Master found at $MASTER..."
                        foundMaster="true"
                        break
                    fi
                done
            done

            echo "sentinel monitor mymaster $MASTER 6379 2" >> /tmp/master
            echo "port 5000
            sentinel resolve-hostnames yes
            sentinel announce-hostnames yes
            $(cat /tmp/master)
            sentinel down-after-milliseconds mymaster 5000
            sentinel failover-timeout mymaster 60000
            sentinel parallel-syncs mymaster 2
            sentinel auth-pass mymaster $REDIS_PASSWORD
            " > /etc/redis/sentinel.conf
            cat /etc/redis/sentinel.conf
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
      containers:
      - name: sentinel
        image: {{ .Values.images.redis.image }}
        command: ["redis-sentinel"]
        args: ["/etc/redis/sentinel.conf"]
        ports:
        - containerPort: 5000
          name: {{ .Values.sentinel }}
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
        - name: data
          mountPath: /data
        {{- if .Values.redisSecretProviderClass.redisSecretName }}
        - name: secrets-store-inline-redis
          mountPath: /etc/csm-authorization/redis
          readOnly: true
        {{- end }}
      volumes:
      - name: redis-config
        emptyDir: {}
      - name: data
        emptyDir : {}
      {{- if .Values.redisSecretProviderClass.redisSecretName }}
      - name: secrets-store-inline-redis
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "{{ .Values.redisSecretProviderClass.redisSecretName }}"
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sentinel }}
spec:
  clusterIP: None
  ports:
  - port: 5000
    targetPort: 5000
    name: sentinel
  selector:
    app: sentinel
---
apiVersion: v1
kind: Service
metadata:
 name: {{ .Values.sentinel }}-svc
spec:
 type: NodePort
 ports:
 - port: 5000
   targetPort: 5000
   nodePort: 32003
   name: {{ .Values.sentinel }}-svc
 selector:
   app: {{ .Values.sentinel }}
