{{- /*
Deprecation notice: use of reverseproxy-config ConfigMap is deprecated and will
be removed in a future release. The ConfigMap remains for backward compatibility
usage only.
*/}}
{{- /*
Use the ConfigMap only if the secretName value is empty or the key is not found
*/}}
{{- if not (.Values.useSecret | default false) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-reverseproxy-config
  namespace: {{ .Release.Namespace }}
data:
{{ tpl (.Files.Glob "conf/config.yaml").AsConfig . | indent 2 }}
{{- end }}
