apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-array-config
  namespace: {{ .Release.Namespace }}
data:
{{ tpl (.Files.Glob "conf/powermax-array-config.yaml").AsConfig . | indent 2 }}
