{{- if ne .Values.deployAsSidecar true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-reverseproxy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Release.Name }}-reverseproxy
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-reverseproxy
    spec:
      serviceAccountName: {{ .Release.Name }}-reverseproxy
      containers:
        - name: csireverseproxy
          image: {{ required "Must provided an image for reverseproxy container." .Values.image }}
          imagePullPolicy: Always
          env:
            - name: X_CSI_REVPROXY_SECRET_PATH
              value: /powermax-reverseproxy-secret/config
            - name: X_CSI_REVPROXY_SECRET_NAME
              value: powermax-reverseproxy-secret
            - name: X_CSI_REVRPOXY_IN_CLUSTER
              value: "true"
            - name: X_CSI_REVPROXY_TLS_CERT_DIR
              value: /app/tls
            - name: X_CSI_REVPROXY_WATCH_NAMESPACE
              value: {{ .Release.Namespace }}
          volumeMounts:
            - name: tls-secret
              mountPath: /app/tls
            - name: cert-dir
              mountPath: /app/certs
            - name: powermax-reverseproxy-secret
              mountPath: /powermax-reverseproxy-secret
      volumes:
        - name: powermax-reverseproxy-secret
          secret:
            secretName: {{ .Release.Name }}-reverseproxy-secret
        - name: tls-secret
          secret:
            secretName: {{ .Values.tlsSecret }}
        - name: cert-dir
          emptyDir:
{{- end }}
