{{- if not (empty .Values.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  config: {{ include "reverseproxy.secret" . | b64enc }}
{{- end }}