apiVersion: v1
kind: ConfigMap
metadata:
  name: common
  namespace: {{ include "custom.namespace" . }}
  labels:
    openpolicyagent.org/policy: rego
data:
  {{- (.Files.Glob "policies/common.rego").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: volumes-create
  namespace: {{ include "custom.namespace" . }}
  labels:
    openpolicyagent.org/policy: rego
data:
  {{- (.Files.Glob "policies/volumes-create.rego").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: volumes-delete
  namespace: {{ include "custom.namespace" . }}
  labels:
    openpolicyagent.org/policy: rego
data:
  {{- (.Files.Glob "policies/volumes-delete.rego").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: volumes-map
  namespace: {{ include "custom.namespace" . }}
  labels:
    openpolicyagent.org/policy: rego
data:
  {{- (.Files.Glob "policies/volumes-map.rego").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: powermax-volumes-create
  namespace: {{ include "custom.namespace" . }}
  labels:
    openpolicyagent.org/policy: rego
data:
  {{- (.Files.Glob "policies/volumes-powermax-create.rego").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: volumes-unmap
  namespace: {{ .Release.Namespace }}
  labels:
    openpolicyagent.org/policy: rego
data:
  {{- (.Files.Glob "policies/volumes-unmap.rego").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sdc-approve
  namespace: {{ .Release.Namespace }}
  labels:
    openpolicyagent.org/policy: rego
data:
  {{- (.Files.Glob "policies/sdc-approve.rego").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: snapshot-create
  namespace: {{ .Release.Namespace }}
  labels:
    openpolicyagent.org/policy: rego
data:
  {{- (.Files.Glob "policies/snapshot-create.rego").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: powerstore-volumes-create
  namespace: {{ include "custom.namespace" . }}
  labels:
    openpolicyagent.org/policy: rego
data:
  {{- (.Files.Glob "policies/volumes-powerstore-create.rego").AsConfig | nindent 2 }}