apiVersion: v1
kind: Secret
metadata:
  name: redis-csm-secret
  namespace: {{ include "custom.namespace" . }}
type: kubernetes.io/basic-auth
stringData:
<<<<<<< HEAD
  password: K@ravi123!
=======
  password: pass1234
>>>>>>> 9057dd8 (REDIS helm chart for auth-proxy)
