{{ if .Values.karaviMetricsPowerscale.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-metrics-powerscale-controller
  namespace: {{ include "custom.namespace" . }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-metrics-powerscale-controller
rules:
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes", "storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes", "nodes"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-metrics-powerscale-controller
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-metrics-powerscale-controller
    namespace: {{ include "custom.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-metrics-powerscale-controller
  apiGroup: rbac.authorization.k8s.io

{{ end }}

