{{ if .Values.karaviMetricsPowerflex.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-metrics-powerflex-controller
  namespace: {{ include "custom.namespace" . }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-metrics-powerflex-controller
rules:
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes", "storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes", "nodes"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-metrics-powerflex-controller
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-metrics-powerflex-controller
    namespace: {{ include "custom.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-metrics-powerflex-controller
  apiGroup: rbac.authorization.k8s.io

{{ end }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-metrics-powerflex-controller
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-metrics-powerflex-controller
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-metrics-powerflex-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-metrics-powerflex-controller
  apiGroup: rbac.authorization.k8s.io
