{{ if .Values.karaviTopology.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-topology-controller
  namespace: {{ include "custom.namespace" . }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-topology-controller
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-topology-controller
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-topology-controller
    namespace: {{ include "custom.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-topology-controller
  apiGroup: rbac.authorization.k8s.io

{{ end }}

