{{- if and (hasKey .Values "metrics") (hasKey .Values.metrics "serviceMonitor") (eq .Values.metrics.serviceMonitor.enabled true) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dell-replication-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: https
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval | default "30s" }}
      scheme: https
      tlsConfig:
        insecureSkipVerify: {{ .Values.metrics.serviceMonitor.insecureSkipVerify | default false }}
{{- end }}
