# Copyright (c) 2025 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

# This action checks the linting errors in yaml files
name: YAML Lint

on:
  pull_request:
    branches: ["**"]

jobs:
  yaml_lint_scan:
    name: Run Yaml Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install yamllint
      - run: yamllint .
