{{- include "redis-csm.validate" . }}
{{- if or .Values.redisPassword .Values.redis.redisPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-csm-secret
  namespace: {{ include "custom.namespace" . }}
type: kubernetes.io/basic-auth
stringData:
  password: {{ required "Redis credentials are required. Set redis.redisPassword." .Values.redisPassword | default .Values.redis.redisPassword }}
  commander_user: {{ required "Redis credentials are required. Set redis.redisUsername." .Values.redisUsername | default .Values.redis.redisUsername }}
{{- end }}
